# Generated by Django 3.2.6 on 2021-11-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_institutionname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='InstitutionShortName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
