# Generated by Django 3.2.6 on 2021-11-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_institutionshortname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='InstitutionName',
            new_name='institutionName',
        ),
    ]
