# Generated by Django 3.2.6 on 2021-11-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_patientinformation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinformation',
            name='user',
        ),
    ]
