# Generated by Django 3.2.6 on 2021-11-12 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211112_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinformation',
            name='user',
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
