# Generated by Django 3.2.6 on 2021-11-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211112_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='InstitutionShortName',
            new_name='institutionShortName',
        ),
    ]
