# Generated by Django 3.2.6 on 2021-11-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_institutionshortname_customuser_institutionshortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='institutionShortName',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
